services:
  - type: web
    name: notice-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python telegram_bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: ICLOUD_EMAIL
        sync: false
      - key: ICLOUD_PASSWORD
        sync: false 